### PR TITLE
Spint

### PR DESCRIPTION
**Pull request by sjsrey**
1. [ ] The justification for this PR is: Update contrib index to include glm and dependencies. This also incorporates a number of merges that happened post the original PR.

### CODE REVIEW

**Comment by TaylorOshan** [comment]
I didn't even realize I had the spintW tests in #847 but not in #861! Two updates for the contrib index...there is no dependency on pandas in spint anymore and the glm ships with everything it needs so no dependency on statsmodels or patsy (doesn't current support formulas).

**Comment by sjsrey** [comment]
I'm still seeing dependencies in the glm directory:

```
contrib/glm - [spint] » grep -n 'import statsmodels' *.py
base.py:412:        >>> import statsmodels.api as sm
base.py:528:        >>> import statsmodels.api as sm
base.py:834:        >>> import statsmodels.api as sm
contrib/glm - [spint] » grep -n 'import patsy' *.py
contrib/glm - [spint] » grep -n 'patsy' *.py
base.py:51:            from patsy import dmatrix
base.py:446:        patsy.DesignInfo.linear_constraint
base.py:448:        from patsy import DesignInfo
base.py:565:        patsy.DesignInfo.linear_constraint
base.py:616:        patsy.DesignInfo.linear_constraint
base.py:629:        from patsy import DesignInfo

```

**Comment by TaylorOshan** [comment]
Ahh, I see it now. It's the inline examples for some of the methods from the LikelihoodModelResults class. I will change with for the methods that I currently test against, such as `con_int()` but will remove the methods that I am not currently testing =, such as `t_test()` and `wald_test()` These will be useful int the future but not imperative to the framework for spint.

**Comment by TaylorOshan** [comment]
I believe I've made all the necessary deletions/edits so there should no longer be unexpected dependencies.

**Pull request merged**
